# .NET 6 build and test 
name: Dotnet - Test
description: Runs format checks and tests on dotnet projects

inputs:
  projects:
    required: false
    type: string
    description: Project's entry file name or pattern
    default: '*.sln'
  filter:
    required: false
    type: string
    description: XUnit filter
    default: ''
   workingDirectory:
    required: false
    type: string
    description: working directory of project
    default: '.'

runs:
  using: "composite"
  defaults:
  run:
    working-directory: ${{ github.event.inputs.workingDirectory || inputs.workingDirectory }}
    shell: bash
  steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Restore dependencies
      run: dotnet restore
      shell: bash

    - name: Run dotnet format
      run: dotnet format --severity warn --verify-no-changes --verbosity detailed
      shell: bash

    - name: Build
      run: dotnet build -c Release --no-restore
      shell: bash

    - name: Run tests
      run: dotnet test -c Release --no-build --verbosity normal `find . -name "${{ github.event.inputs.projects || inputs.projects }}"` --filter "${{ github.event.inputs.filter || inputs.filter }}"
      shell: bash
