name: AKS Deployment

on:
  workflow_call:
    inputs:
      serviceName:
        required: true
        type: string
      currentTag:
        required: true
        type: string
      namespace:
        required: true
        type: string
      environment:
        required: true
        type: string
      context:
        required: true
        type: string
      downloadArtifactFromCurrentRun:
        required: false
        default: true
        type: boolean
      downloadArtifactFromWorkflow:
        required: false
        default: deployment.yaml
        type: string
    secrets:
      KUBECONFIG:
        required: true

jobs:
  deploy:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v2
        if: ${{ !inputs.downloadArtifactFromCurrentRun }}
        with:
          workflow: ${{ inputs.downloadArtifactFromWorkflow }}
      
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        if: ${{ inputs.downloadArtifactFromCurrentRun }}
        with:
          path: ${{ inputs.serviceName }}/
          
      - name: Helm Upgrade
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --kube-context ${{ inputs.context }} --namespace ${{ inputs.namespace }} --install --values ./charts/values-${{ inputs.environment }}.yaml --set serviceVersion=${{ inputs.currentTag }} --wait --atomic --timeout 300s ${{ inputs.serviceName }} ${{ inputs.serviceName }}/${{ inputs.serviceName }}-1.0.0.tgz
          kubeconfig: '${{ secrets.KUBECONFIG }}'
