name: AKS Deployment
on:
  workflow_call:
    inputs:
      serviceName:
        required: true
        type: string
      currentTag:
        required: true
        type: string
      namespace:
        required: true
        type: string
      environment:
        required: true
        type: string
      context:
        required: true
        type: string
    secrets:
      KUBECONFIG:
        required: true
  workflow_dispatch:
    inputs:
      serviceName:
        required: true
        description: Service Name
      currentTag:
        required: true
        description: Image Version
      namespace:
        required: true
        description: Namespace
      environment:
        required: true
        description: Environment (dev, test, prod)
        default: test
      context:
        required: true
        description: Kubernetes context name
        default: tmf-tst-centralus-aks

jobs:
  deploy:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifacts
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.serviceName }}

      - name: Download Artifacts
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: deployment.yaml
          workflow_conclusion: success

      - name: Helm Upgrade
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --kube-context ${{ inputs.context }} --namespace ${{ inputs.namespace }} --install --values ./charts/values-${{ inputs.environment }}.yaml --set serviceVersion=${{ inputs.currentTag }} --wait --atomic --timeout 300s ${{ inputs.serviceName }} ${{ inputs.serviceName }}-1.0.0.tgz
          kubeconfig: '${{ secrets.KUBECONFIG }}'

      - name: Helm Upgrade
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --kube-context ${{ github.event.inputs.context }} --namespace ${{ github.event.inputs.namespace }} --install --values ./charts/values-${{ github.event.inputs.environment }}.yaml --set serviceVersion=${{ github.event.inputs.currentTag }} --wait --atomic --timeout 300s ${{ github.event.inputs.serviceName }} ${{ github.event.inputs.serviceName }}/${{ github.event.inputs.serviceName }}-1.0.0.tgz
          kubeconfig: '${{ secrets.KUBECONFIG }}'