name: AKS Deployment
description: Deploy a Helm application to Kubernetes in AKS.

on:
  workflow_call:
    inputs:
      serviceName:
        required: true
        type: string
      currentTag:
        required: true
        type: string
      namespace:
        required: true
        type: string
      environment:
        required: true
        type: string
      context:
        required: true
        type: string
    secrets:
      KUBECONFIG:
        required: true

jobs:
  deploy:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment || inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: deployment.yaml
          workflow_conclusion: success

      - name: Helm Upgrade
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --kube-context ${{ github.event.inputs.context || inputs.context }} --namespace ${{ github.event.inputs.namespace || inputs.namespace }} --install --values ./charts/values-${{ github.event.inputs.environment || inputs.environment }}.yaml --set serviceVersion=${{ github.event.inputs.currentTag || inputs.currentTag }} --wait --atomic --timeout 300s ${{ github.event.inputs.serviceName || inputs.serviceName }} ${{ github.event.inputs.serviceName || inputs.serviceName }}/${{ github.event.inputs.serviceName || inputs.serviceName }}-1.0.0.tgz
          kubeconfig: '${{ secrets.KUBECONFIG }}'
