name: AKS Deployment

on:
  workflow_call:
    inputs:
      serviceName:
        required: true
        type: string
      currentTag:
        required: true
        type: string
        description: "github sha"
      namespace:
        required: true
        type: string
      environment:
        required: true
        type: string
        description: "dev test prod"
      context:
        required: true
        type: string
    secrets:
      KUBECONFIG:
        required: true

jobs:
  deploy:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.currentTag }}

      - name: Create folder for rendered charts
        run: mkdir -p path/to/charts

      - name: Package Dev
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm package charts/${{ inputs.serviceName }} --namespace ${{ inputs.namespace }} --destination path/to/charts

      - name: Helm Upgrade
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --kube-context ${{ inputs.context }} --namespace ${{ inputs.namespace }} --install --values ./charts/values-${{ inputs.environment }}.yaml --set serviceVersion=${{ inputs.currentTag }} --wait --atomic --timeout 300s ${{ inputs.serviceName }} path/to/charts/${{ inputs.serviceName }}-1.0.0.tgz
          kubeconfig: '${{ secrets.KUBECONFIG }}'
