name: Docker - Build, Push

on:
  workflow_call:
    inputs:
      serviceName:
        required: true
        type: string
      currentTag:
        required: true
        type: string
    secrets:
      azureCredentials:
        required: true
      registryLoginServer:
        required: true
      resourceGroup:
        required: true
      registryUsername:
        required: true
      registryPassword:
        required: true
      snykToken:
        required: true


jobs:
  build-and-push-image:
    name: Build and Push Stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set Job-Environment Variables
        run: echo "IMAGE_NAME=${{ secrets.registryLoginServer }}/${{ inputs.serviceName }}" >> $GITHUB_ENV

      - name: AZ login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azureCredentials }}

      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.registryLoginServer }}
          username: ${{ secrets.registryUsername }}
          password: ${{ secrets.registryPassword }}

      - name: Build images
        run: |
          docker build . -t ${IMAGE_NAME}:${{ inputs.currentTag }}
          docker build . -t ${IMAGE_NAME}:latest

      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.snykToken }}
        with:
          image: ${{ secrets.registryLoginServer }}/${{ inputs.serviceName }}:${{ inputs.currentTag }}

      - name: Push images to registry container
        run: |
          docker push ${IMAGE_NAME}:${{ inputs.currentTag }}
          docker push ${IMAGE_NAME}:latest
