name: Docker - Build, Push
on:
  workflow_call:
    inputs:
      serviceName:
        required: true
        type: string
      currentTag:
        required: true
        type: string
    secrets:
      azureCredentials:
        required: true
      registryLoginServer:
        required: true
      resourceGroup:
        required: true
      registryUsername:
        required: true
      registryPassword:
        required: true


jobs:
  build-and-push-image:
    name: Build and Push Stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set Job-Environment Variables
        run: echo "IMAGE_NAME=${{ secrets.registryLoginServer }}/${{ github.event.inputs.serviceName || inputs.serviceName }}" >> $GITHUB_ENV

      - name: AZ login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azureCredentials }}

      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.registryLoginServer }}
          username: ${{ secrets.registryUsername }}
          password: ${{ secrets.registryPassword }}
      - name: Build and push image
        run: |
          docker build . -t ${IMAGE_NAME}:${{ github.event.inputs.currentTag || inputs.currentTag }}
          docker build . -t ${IMAGE_NAME}:latest
          docker push ${IMAGE_NAME}:${{ github.event.inputs.currentTag || inputs.currentTag }}
          docker push ${IMAGE_NAME}:latest

      - name: Deploy to registry - current
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.resourceGroup }}
          dns-name-label: ${{ secrets.resourceGroup }}${{ github.run_number }}
          image: ${{ env.IMAGE_NAME }}:${{ github.event.inputs.currentTag || inputs.currentTag }}
          registry-login-server: ${{ secrets.registryLoginServer }}
          registry-username: ${{ secrets.registryUsername }}
          registry-password: ${{ secrets.registryPassword }}
          name: ${{ github.event.inputs.serviceName || inputs.serviceName }}
          location: 'central us'

      - name: Deploy to registry - latest
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.resourceGroup }}
          dns-name-label: ${{ secrets.resourceGroup }}${{ github.run_number }}
          image: ${{ env.IMAGE_NAME }}:latest
          registry-login-server: ${{ secrets.registryLoginServer }}
          registry-username: ${{ secrets.registryUsername }}
          registry-password: ${{ secrets.registryPassword }}
          name: ${{ github.event.inputs.serviceName || inputs.serviceName }}
          location: 'central us'
