name: Helm Package

on:
  workflow_call:
    inputs:
      serviceName:
        required: true
        type: string
      namespace:
        required: true
        type: string

jobs:
  package:
    name: Package helm chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create folder for rendered charts
        run: mkdir -p path/to/charts

      - name: Package Dev
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm package charts/${{ inputs.serviceName }} --namespace ${{ inputs.namespace }} --destination path/to/charts

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.serviceName }}
          path: path/to/charts
