name: Snyk - Docker

on:
  workflow_call:
    inputs:
      containerRegistryUrl:
        required: true
        type: string
      imageName:
        required: true
        type: string
      imageTag:
        required: true
        type: string
    secrets:
      snykToken:
        required: true

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.snykToken }}
      with:
        image: ${{ inputs.containerRegistryUrl }}/${{ inputs.imageName }}/${{ inputs.imageTag }}