name: Snyk - Node

on:
  workflow_call:
    secrets:
      snykToken:
        required: true

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.snykToken }}
        with:
          args: --fail-on=all --severity-threshold=high
